# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true
sudo: required

r_github_packages:
  - jimhester/covr

before_install:
  - openssl aes-256-cbc
      -K $encrypted_effddfd5c5ef_key -iv $encrypted_effddfd5c5ef_iv
      -in tests/testthat/api_key.txt.enc -out ~/api_key.txt -d

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change



after_success:
  - Rscript -e 'covr::codecov()'
